### ISSUE TITLE
First Draft for Onboarding Merchants

### ISSUE THREAD

**Issue by Suyog007** [venture-23/localcoin#10]
We need to create an draft initial tools for onboarding merchants and users.

**Comment by dbrehmer** [comment]
[LocalCoin Merchant Brochure.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEh5QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--503de1c156b408c0c0eb3f352edde4a06c4c8a52/LocalCoin%20Merchant%20Brochure.pdf)
[LocalCoin Merchant Brochure.pdf.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFR5QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6e12dc736aa2884da5a2eb7fa3041d94200121e0/LocalCoin%20Merchant%20Brochure.pdf.zip)

Brochures complete.
